travis:
  secure:
    BINSTAR_TOKEN: LAG3Q7Q/+RXD6qvbJCQksWA7RIRxYgUJsITVF2JdLhYqvgB9XvRSkjSxjxmUevdeRZJJykIv8zlBFGLP7FZ+/4J23Vdy1YJOP0NQIXkBK/jzO5CSQ4tEms25JmYBNtZMOt+2HlpSChuwZIu4Qq+3drfHEJJsKWQOrc8sCnJWpJ5PNr5uILlNd/bO0uUEVm45BVHpVZR52egtzmkjrmC6jRMCcaa/8XtgpXfNmfMR+KKPavIHW0HQIU9WUqj3NNJdvN6s4wmGxEPG01LMSa239er0NV6wn3d+lQTi47qU41hJoP85NQ5TIJ48Dq7/EFcmqgHJMO3csf5B325WgBLA7W35EdfI3oL8VQZv7we3LxlUwLaxlJXmtXSIgDH+DsgYB0s2EQ6+1gP+jrocTOACN82cxRRuP00Xk79Ky+o5Ur8YbgMpH8Nt8HlepQ0u5IxJamX/HOWJCfn4VhhmKHA6BSQiJSdKrBN9gC6NXJOOQ6+wCW2/6D1C9uRr/rZ45TrsVOKO6gqII/P5Aa8xM3iy/wOO8S0AMMnSCirIcxif+KN8CcVX432m5TkWz6kugjQrZSGt9pIwcDql30gO2aVdyOITQxoUEwmlN3Uo0EwP4iBNGWZkorIJsqJXXcUYgxJ5xCXxxbXYiAWKseApbIJNXfhZ+cH0jY6PujHW/pdfQOg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
