travis:
  secure:
    BINSTAR_TOKEN: jgMfy/6fHSlCclWXnkeFlcF7VEK15wUqSvFUP4Qt8E8mv+HNrBu0lKlhr+/WMeh7kH9RspJePdmHMuVhqweAyRtuV1ACqd0tTay4FefW/RgeOxau2J5xxS/5YJmd2SgOIxr8diZemLAQ8reRz7zT8ZtCNs0qLYiEGOaHOg9fahfeRu4qu7snRf8vRPsFutYI6SeiQK86amg49nAznOqnUY5+NzGBCJszoi1Ef3AybyeCb8FFIUgNPGTpvSrbwlKbZxfJP1Tn/ptkIGB/YOZbAWn77oYursgURCnwFzNCKj6KDA150dWpOKQl8lxqz5mNbmqwzMKdg9cwXEaYq2bX0hSgLnpkxNi6xX9KQpnwN8YG5v1fhdyOv27x503WKriHsnKPHyI8Y0DblWuwwHdmyhrmpgXVBNqJuMySOfdt5t8iHt7lo2FeXi9a7UDhvuk03czUApBVIJ0OYrUYmnem9r+ZtekviO+34ERBtc0L2WtxCe8WL+Lxx/u6lHJJZ9A6G1tB7Z5vjdAB5e5dRFRHnjzUbNyYXSZm7B1y4ak3AdkTRVLATmjA3tvv2nRPTjZG3kt+q46yfPRyTD2RG+3MYZCKtdTxx3W7FnbSVvdseoeQfdO49d+tTnEZO5MX4KoPt2rRp8scmYfcCuRiSPVoxBeU8ouRTdIa2lA8wpigxiQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
